youtube/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from video import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.HomeView.as_view(), name = 'home'),
    path('detail/<int:pk>', views.VideoDetailView.as_view(), name = 'video-detail'),
    path('upload/', views.VideoUpload.as_view(), name = 'video-upload')
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

video/models.py
from django.db import models
from django.conf import settings


class CommentQuerySet(models.query.QuerySet):
    def get_video_comments(self, **kwargs):
        vid = Video.objects.get(pk = kwargs['pk'])
        comments = self.filter(video = vid)
        return comments

class Video(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete = models.CASCADE,
                            related_name = 'uploader')
    video_url = models.FileField(upload_to = 'videos/', null = True, verbose_name = '')
    title = models.CharField(max_length = 200)
    description = models.TextField(max_length = 600)

    def __str__(self):
        return self.heading

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete = models.CASCADE,
                            related_name = 'commenter')
    video = models.ForeignKey(Video, on_delete = models.CASCADE)
    comment = models.CharField(max_length = 400)
    objects = CommentQuerySet.as_manager()
    
    def __str__(self):
        return self.comment

video/forms.py
from django import forms
from django.forms import ModelForm

from video.models import Video, Comment

class VideoForm(ModelForm):
    class Meta:
        model = Video
        fields = ('title',
                    'description',
                    'video_url')

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)
        widgets = {
            'text': forms.TextInput(attrs={
                'id': 'post-text', 
                'required': True, 
                'placeholder': 'Say something...'
            }),
        }

video/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils import timezone

from video.models import Video, Comment
from video.forms import VideoForm, CommentForm

# Create your views here.
#create a view for the uplaoding video
#create a view for detail view for the video
#create a view for uploading a comment
#create a view to lsit all the videos

class VideoUpload(FormView):
    template_name = 'video/video_upload.html'
    form_class = VideoForm
    def form_valid(self, form):
        import pdb; pdb.set_trace()
        video = form.save(commit = False)
        video.user = self.request.user
        video.save()
        return redirect('home')
    
class HomeView(ListView):
    model = Video

class VideoDetailView(DetailView):
    model = Video
    template_name = 'video/video_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time'] = timezone.now()
        context['comment_form'] = CommentForm()
        # import pdb; pdb.set_trace()
        video_key = self.kwargs['pk']
        comments = Comment.objects.get_video_comments(pk = video_key)
        context['comments'] = comments
        return context

    def post(self, *args, **kwargs):
        # import pdb; pdb.set_trace()
        comment_text = self.request.POST.get('comment')
        vid = Video.objects.get(pk = self.kwargs['pk'])
        comment = Comment(user = self.request.user, video = vid, comment = comment_text)
        comment.save()
        response_data = {}
        response_data['result'] = 'successfully created the comment'
        response_data['comment_text'] = comment.comment
        response_data['author'] = self.request.user.username
        response_data['pk'] = comment.pk
        return HttpResponse(json.dumps(response_data),
                                content_type = 'application/json')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Youtube</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/main.css' %}">
</head>
<body>
    <div class = 'fix-fix'>
        <div class = 'nav-bar'>
            <div class = 'host-name'>
                <img src="{% static 'images/youtube-logo.png' %}" alt="youtube-log" class = 'host-name'>
            </div>
            <div class = 'upload'>
                <button class = 'upload-btn'><a href="{% url 'video-upload' %}">Upload Video</a></button>
            </div>
        </div>   
    </div>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

templates/video/video_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h1 id = 'pk'>{{ object.pk }}</h1><br>
    <div class = 'video-detail'>
        <video width="760" height="570" controls autoplay muted='muted' class = 'video-tag'>
            <source src= "{{ MEDIA_URL }}{{ object.video_url }}" type="video/mp4"z>
        </video>
        <h1>{{ object.title }}</h1>
        <p>{{ object.description }}</p>
        <hr>
        
        <div id = 'all-comments'>
            {% for comment in comments %}
                <div class = 'comment-block'>
                    <p class = 'comment-user'><strong>{{ comment.user.username }}</strong></p>
                    <p class = 'single-comment'>{{ comment.comment }}</p>
                </div>
            {% empty %}
                <!-- <p>No comments yet.</p> -->
            {% endfor %}
        </div>
        <hr>
        <form method="post" enctype="multipart/form-data" id = 'post-form'>
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="add comment" id='comment-btn'>
        </form>
    </div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

<script>
    $('#post-form').on('submit' , function(event){
        event.preventDefault();
        console.log('haa just submitted');
        create_post()
    })
    let pk = $('#pk').text()
    function create_post(){
        console.log('haa just entered create post')
        console.log($('#post-form').val())
        $.ajax({
            url : String(pk),
            type : "POST",
            data : {comment : $('#id_comment').val()},
            success: function(json){
                $('#post-form').val('')
                console.log('entered success function')
                console.log(json)
                $('#all-comments').prepend("<div class = 'comment-block'> <p class = 'comment-user'><strong>"+json.author+"</strong></p>"+"<p class = 'single-comment'>"+json.comment_text+"</p> </div>")
                console.log("success")
            }
        })
    }
    
</script>

<script>
    $(function() {


    // This function gets cookie with a given name
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    /*
    The functions below will create a header with csrftoken
    */

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
        // test that a given url is a same-origin URL
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    });
</script>

{% endblock %}

templates/video/video_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class = 'home-image'>
        <img src="{% static 'images/home-image.jpg' %}" alt="home-image" class = 'wide-image'>
    </div>

    <h1 class = 'home-head'>Videos</h1>
    <!-- <ul>
    {% for video in object_list %}
        <li>{{ video.title }}</li>
        <li>{{ video.video_url }}</li>
    {% empty %}
        <li>No videos yet.</li>
    {% endfor %}
    </ul> -->
    <div class = 'gallery-list'>
    {% for video in object_list %}
        <div class = 'gallery'>
            <div class = 'thumbnail'>
                <a href="{% url 'video-detail' video.id %}" >
                    <img src="{% static 'images/vid4.jpg' %}" alt="Cinque Terre" class = 'thumbnail-image'>
                </a>

                <div class = 'heading'>
                    <div>
                        <strong class = 'heading-text'>{{ video.title }}</strong><br>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <h3>No videos yet</h3>
    {% endfor %}
    </div>
{% endblock %}

templates/video/video_upload.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="post" enctype="multipart/form-data" id = 'upload-form'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="upload">
</form>

{% endblock %}